package com.canbazdev.myreminders.util

object Constants {
    const val PREFERENCE_NAME = "REMINDERS"

    const val DATA_SAVED_FIRST_TIME = "FIRST_TIME"
//    const val PREF_IS_LANGUAGE_SELECTED = "PREF_IS_LANGUAGE_SELECTED"
//    const val PREF_CURRENT_SELECTED_LANGUAGE = "PREF_CURRENT_SELECTED_LANGUAGE"
//    const val PREF_CONTACT_EMAIL = "PREF_CONTACT_EMAIL"
//    const val PREF_SHARE_MESSAGE = "PREF_SHARE_MESSAGE"
//    const val PREF_MINIMUM_APP_VERSION = "PREF_MINIMUM_APP_VERSION"


}